import { TenderV2, TabItemV2 } from "./types";

export const TABS_V2: TabItemV2[] = [
  {
    id: "overview",
    stepNumber: 1,
    label: "Overview & Scope",
    subtitle: "Parameters & AI Copilot",
    iconName: "FileText",
  },
  {
    id: "eligibility",
    stepNumber: 2,
    label: "Eligibility & Gates",
    subtitle: "Scorecard & Rules",
    iconName: "ShieldCheck",
  },
  {
    id: "payment",
    stepNumber: 3,
    label: "Payment Proof",
    subtitle: "EMD & Cover-1 Slip",
    iconName: "CreditCard",
  },
  {
    id: "proposal",
    stepNumber: 4,
    label: "Proposal Desk",
    subtitle: "AI Technical Drafts",
    iconName: "PenLine",
  },
  {
    id: "binder",
    stepNumber: 5,
    label: "PDF Binder",
    subtitle: "Master Pack & Export",
    iconName: "Library",
  },
];

export const STATIC_TENDERS_V2: TenderV2[] = [
  {
    id: "tender-sajha-69",
    tenderNumber: "SAJHA/69",
    title: "Development of Integrated Website and Mobile Application for Sports Authority of Jharkhand (SAJHA)",
    organization: "Sports Authority of Jharkhand (SAJHA)",
    department: "Department of Tourism, Arts, Culture, Sports & Youth Affairs",
    location: "Ranchi, Jharkhand",
    publishDate: "02 Mar 2026",
    submissionDeadline: "28 Mar 2026, 03:00 PM",
    technicalOpeningDate: "29 Mar 2026, 11:30 AM",
    estimatedValueDisplay: "₹1,50,00,000 (₹1.50 Cr)",
    tenderFeeDisplay: "₹5,900 (₹5,000 + 18% GST)",
    emdDisplay: "₹5,00,000",
    emdStatus: "Verified",
    readinessScore: 76,
    winProbability: 72,
    decision: "GO",
    status: "In Analysis",
    submissionMode: "Online (Jharkhand e-Procurement Portal)",
    turnoverRequired: "₹1.50 Cr",
    companyTurnover: "₹16.20 Cr",
    scopeSummary: "Sports Authority of Jharkhand (SAJHA) requires a turnkey partner for end-to-end design, cloud architecture, native mobile applications (iOS & Android), athlete enrollment portal, tournament management with live scoring, and 3-year post-deployment maintenance support.",
    keyDates: [
      { label: "RFP Publication", date: "02 Mar 2026", isPassed: true },
      { label: "Pre-Bid Query Deadline", date: "12 Mar 2026", isPassed: true },
      { label: "Bid Submission Deadline", date: "28 Mar 2026, 03:00 PM", isPassed: false },
      { label: "Technical Bid Opening", date: "29 Mar 2026, 11:30 AM", isPassed: false },
    ],
    tags: ["Mobile App", "Web Portal", "e-Governance", "Sports Tech", "Cloud Native"],
    commercialTerms: {
      contractDuration: "12 Months (Dev) + 36 Months (O&M Support)",
      performanceSecurityPBG: "5% of Contract Value (within 15 days of LoA)",
      bidValidity: "180 Days from Bid Submission Deadline",
      penaltyClause: "0.5% per week of delay, max capped at 10%",
      coversCount: "2-Cover System (Cover 1: Fee & Tech, Cover 2: Financial BOQ)",
      consortiumRule: "Sole Bidder Only (Consortium / Sub-contracting Not Allowed)",
      msmePolicy: "EMD Exempt: Yes (Rule 170 GFR) | Turnover Waiver: Not Applicable",
    },
    paymentMilestones: [
      {
        phase: "Phase 1",
        percentage: "20%",
        milestoneTitle: "SRS, Architecture & UI/UX Signoff",
        description: "Delivery of System Requirement Specification, high-fidelity Figma prototypes, and cloud architecture blueprint.",
      },
      {
        phase: "Phase 2",
        percentage: "30%",
        milestoneTitle: "Beta Build & UAT Completion",
        description: "Development of web portal, iOS & Android apps, staging environment deployment, and successful UAT signoff.",
      },
      {
        phase: "Phase 3",
        percentage: "30%",
        milestoneTitle: "CERT-In Security Audit & Final Go-Live",
        description: "Safe-to-host certification by CERT-In empaneled auditor, app store publish, and production launch.",
      },
      {
        phase: "Phase 4",
        percentage: "20%",
        milestoneTitle: "Quarterly O&M Support & SLA",
        description: "Disbursed in 12 equal quarterly installments across 3-year maintenance cycle based on SLA uptime.",
      },
    ],
    sourceDocuments: [
      {
        id: "doc-1",
        name: "RFP_SAJHA_Website_MobileApp_2026.pdf",
        size: "8.4 MB",
        pages: 142,
        type: "RFP",
        date: "02 Mar 2026",
      },
    ],
    requirements: [
      {
        id: "req-1",
        category: "financial",
        categoryLabel: "Financial Turnover",
        title: "Minimum Average Annual Turnover",
        ruleDescription: "The bidder must have an average annual financial turnover of at least ₹1.50 Crore during the last 3 financial years (FY 2022-23, FY 2023-24, FY 2024-25).",
        thresholdValue: "₹1.50 Cr Average Turnover",
        proofRequired: "Audited Balance Sheets with CA Certificate and UDIN.",
        mandatory: true,
        iconName: "TrendingUp",
      },
      {
        id: "req-2",
        category: "experience",
        categoryLabel: "Past Project Experience",
        title: "Minimum 3 Completed Government Projects",
        ruleDescription: "The bidder must have successfully executed and completed at least 3 software development / web portal / mobile app projects for Central/State Govt, PSUs, or Autonomous Bodies in the last 5 years.",
        thresholdValue: "3+ Completed Projects",
        proofRequired: "Client Work Orders, Agreement copies, and Work Completion / Satisfactory Certificates.",
        mandatory: true,
        iconName: "FolderGit2",
      },
      {
        id: "req-3",
        category: "vintage",
        categoryLabel: "Company Operational Vintage",
        title: "Minimum 3+ Years in IT/Software Operations",
        ruleDescription: "The bidding entity must be incorporated and actively operating in software engineering, mobile apps, and IT consulting services for at least 3 continuous years prior to RFP date.",
        thresholdValue: "3+ Years Active Operations",
        proofRequired: "Certificate of Incorporation (ROC / MCA) and Memorandum of Association (MoA).",
        mandatory: true,
        iconName: "Building2",
      },
      {
        id: "req-4",
        category: "manpower",
        categoryLabel: "Team & Manpower Strength",
        title: "Minimum 25+ In-House Technical Professionals",
        ruleDescription: "The agency must have at least 25 full-time qualified IT personnel (Project Managers, UI/UX Designers, Cloud Engineers, Full-Stack Devs, QA) on its active payroll.",
        thresholdValue: "25+ Full-Time Engineers",
        proofRequired: "EPF (Employees' Provident Fund) electronic challan returns / HR payroll declaration.",
        mandatory: true,
        iconName: "Users",
      },
      {
        id: "req-5",
        category: "certifications",
        categoryLabel: "Quality & Security Accreditations",
        title: "Active ISO 9001 & ISO 27001 Certifications",
        ruleDescription: "The bidder must possess valid and active certifications for ISO 9001:2015 (Quality Management) and ISO 27001:2013 (Information Security Management) or CMMI Level 3.",
        thresholdValue: "ISO 9001 & ISO 27001 / CMMI L3",
        proofRequired: "Valid copies of accreditation certificates issued by accredited certification bodies.",
        mandatory: true,
        iconName: "Award",
      },
      {
        id: "req-6",
        category: "legal",
        categoryLabel: "Debarment & Legal Undertaking",
        title: "Non-Blacklisting Undertaking",
        ruleDescription: "The bidder must not have been debarred, blacklisted, or banned by any Central/State Government department, PSU, or multilateral agency as of bid date.",
        thresholdValue: "Clean Legal Record",
        proofRequired: "Self-Declaration on ₹100 Non-Judicial Stamp Paper duly notarized.",
        mandatory: true,
        iconName: "ShieldAlert",
      },
      {
        id: "req-7",
        category: "legal",
        categoryLabel: "Statutory Registrations",
        title: "Valid GSTIN, PAN, and Tax Compliance",
        ruleDescription: "The bidder must hold an active PAN card, GST registration in India, and have filed up-to-date Income Tax and GST returns.",
        thresholdValue: "Active PAN & GSTIN",
        proofRequired: "GST Registration Certificate, PAN card copy, and latest 2 quarters GSTR-3B filings.",
        mandatory: true,
        iconName: "FileCheck2",
      },
    ],
    disqualificationGates: [
      {
        id: "gate-1",
        category: "Financial Gate",
        title: "Annual Turnover Eligibility Threshold",
        requiredValue: "Min. ₹1.50 Cr Avg. (Last 3 FYs)",
        companyValue: "₹16.20 Cr Average (10.8x Buffer)",
        status: "PASS",
        note: "Audited balance sheets for FY 2022-23 (₹14.8 Cr), 2023-24 (₹16.1 Cr), 2024-25 (₹17.7 Cr) verified in Vault with CA UDIN.",
        proofDocumentName: "CA_Audited_Turnover_Cert_UDIN_2025.pdf",
        iconName: "TrendingUp",
      },
      {
        id: "gate-2",
        category: "Experience Gate",
        title: "Prior Government Project Track Record",
        requiredValue: "Min. 3 Completed Govt/PSU Projects",
        companyValue: "4 Completed Govt Portal Contracts",
        status: "PASS",
        note: "Verified contracts: UP Tourism Portal (₹1.8 Cr), Bihar Land Records App (₹95L), Jharkhand e-Pass System (₹1.2 Cr), IRCTC Rail Mitra (₹2.4 Cr).",
        proofDocumentName: "Govt_Project_Completion_Dossier_4Projects.pdf",
        iconName: "FolderGit2",
      },
      {
        id: "gate-3",
        category: "Corporate Vintage",
        title: "Entity Incorporation & Operational Age",
        requiredValue: "Min. 3+ Years Active in IT/Software",
        companyValue: "6 Years Active (Incorporated 2019)",
        status: "PASS",
        note: "Certificate of Incorporation (CIN: U72900MH2019PTC328491) verified with MCA records.",
        proofDocumentName: "Certificate_of_Incorporation_MCA.pdf",
        iconName: "Building2",
      },
      {
        id: "gate-4",
        category: "Manpower Strength",
        title: "Dedicated Full-Time Software Engineers",
        requiredValue: "Min. 25+ Technical Staff on Payroll",
        companyValue: "42 Full-Time IT Personnel on Active ECR",
        status: "PASS",
        note: "Latest EPF Electronic Challan Return (ECR) for Feb 2026 matches required strength (42 contributing members).",
        proofDocumentName: "EPF_ECR_Challan_Feb_2026.pdf",
        iconName: "Users",
      },
      {
        id: "gate-5",
        category: "Quality Accreditations",
        title: "ISO 9001 & ISO 27001 Security Certifications",
        requiredValue: "Active ISO 9001 & ISO 27001 / CMMI L3",
        companyValue: "ISO 9001 (Valid) · ISO 27001 (Expiring 15 Apr)",
        status: "ACTION_REQUIRED",
        note: "ISO 27001 certificate expires on 15 Apr 2026 (prior to technical bid opening). Renewal audit completed — attach renewal letter.",
        proofDocumentName: "ISO_9001_and_ISO_27001_Certificates.pdf",
        iconName: "Award",
      },
      {
        id: "gate-6",
        category: "Legal Compliance",
        title: "Non-Blacklisting & Clean Track Record",
        requiredValue: "Clean Legal Record / No Debarment",
        companyValue: "Clean Record (No Debarment)",
        status: "PASS",
        note: "Notarized Affidavit on ₹100 stamp paper signed by Managing Director ready in Vault.",
        proofDocumentName: "Non_Blacklisting_Affidavit_Notarized.pdf",
        iconName: "ShieldAlert",
      },
    ],
    vaultAuditDocuments: [
      {
        id: "vdoc-1",
        name: "Certificate of Incorporation (ROC / MCA)",
        category: "Corporate Registration",
        status: "verified",
        issueDate: "14 May 2019",
        fileSize: "1.2 MB",
        message: "CIN: U72900MH2019PTC328491 · Verified Active",
      },
      {
        id: "vdoc-2",
        name: "GSTIN & PAN Permanent Statutory Record",
        category: "Tax Compliance",
        status: "verified",
        issueDate: "Permanent",
        fileSize: "850 KB",
        message: "GSTIN: 27AABCT8291M1Z8 · Active & Regular",
      },
      {
        id: "vdoc-3",
        name: "3-Year Audited Balance Sheets with CA UDIN",
        category: "Financial Record",
        status: "verified",
        issueDate: "FY 2022-25",
        fileSize: "4.6 MB",
        message: "Avg. Turnover: ₹16.20 Cr · Net Worth Positive",
      },
      {
        id: "vdoc-4",
        name: "4 Govt Project Completion Certificates & LoAs",
        category: "Work Experience",
        status: "verified",
        issueDate: "2021 - 2025",
        fileSize: "6.2 MB",
        message: "Cumulative Value: ₹6.35 Cr · Client Performance A+",
      },
      {
        id: "vdoc-5",
        name: "ISO 9001:2015 Quality Management Certificate",
        category: "Quality Accreditation",
        status: "verified",
        expiryDate: "20 Nov 2027",
        fileSize: "1.4 MB",
        message: "Accredited Body: TUV SUD · Status: Valid",
      },
      {
        id: "vdoc-6",
        name: "ISO 27001:2013 Information Security Certificate",
        category: "Security Accreditation",
        status: "action_needed",
        expiryDate: "15 Apr 2026",
        fileSize: "1.8 MB",
        message: "Renewal Needed: Expires in 15 days (Attach Renewal Acknowledgement)",
      },
      {
        id: "vdoc-7",
        name: "Notarized Non-Blacklisting Affidavit (₹100 Stamp)",
        category: "Legal Undertaking",
        status: "verified",
        issueDate: "05 Mar 2026",
        fileSize: "920 KB",
        message: "Director Sign & Notary Stamp Verified",
      },
    ],
    qcbsScores: [
      {
        parameter: "1. Financial Strength & Annual Turnover",
        maxMarks: 20,
        earnedMarks: 20,
        evaluationBasis: "Turnover > ₹10 Cr awards max 20 marks (Company: ₹16.20 Cr).",
      },
      {
        parameter: "2. Past Experience in Web & Mobile Applications",
        maxMarks: 30,
        earnedMarks: 25,
        evaluationBasis: "4 completed contracts (Max marks for 5+ contracts).",
      },
      {
        parameter: "3. Team Strength & Key Technical Personnel",
        maxMarks: 20,
        earnedMarks: 15,
        evaluationBasis: "42 full-time staff on ECR payroll (15 marks awarded for 35+).",
      },
      {
        parameter: "4. Quality & Security Certifications (ISO 9001 / 27001)",
        maxMarks: 20,
        earnedMarks: 16,
        evaluationBasis: "ISO 9001 valid (10 marks) + ISO 27001 renewal in progress (6/10).",
      },
      {
        parameter: "5. Technical Approach & Solution Understanding",
        maxMarks: 10,
        earnedMarks: 0,
        evaluationBasis: "Will be compiled from AI Technical Drafts in Step 4 (Proposal Desk).",
      },
    ],
    riskRadarItems: [
      {
        id: "risk-1",
        severity: "medium",
        title: "ISO 27001 Certificate Expiry prior to Bid Opening",
        riskDescription: "The current ISO 27001 certificate expires on 15 April 2026. If the technical evaluation happens after 15 April, the committee might seek clarification.",
        mitigationStrategy: "Attach the ISO 27001 Re-Certification Audit Acknowledgement & Stage-2 recommendation letter alongside the existing certificate in Cover-1.",
      },
      {
        id: "risk-2",
        severity: "low",
        title: "Client Completion Certificate #2 (Bihar Project) Date Alignment",
        riskDescription: "The completion certificate shows project completion date as Jan 2024 whereas agreement had end date of Nov 2023.",
        mitigationStrategy: "Attach the official contract extension letter issued by the client authority to avoid any query regarding liquidated damages.",
      },
    ],
    signatoryDetails: {
      companyName: "Tech Solutions Pvt Ltd",
      hqLocation: "Tech Park, GS Road, Guwahati & Andheri East, Mumbai",
      pan: "AABCT8291M",
      gstin: "27AABCT8291M1Z8",
      cin: "U72900MH2019PTC328491",
      udyamRegistration: "UDYAM-MH-19-0048291",
      signatoryName: "Vikas Kumar",
      signatoryTitle: "Director & Authorized Bid Representative",
      signatoryEmail: "vikasfrontenddeveloper007@gmail.com",
      signatoryPhone: "+91 98765 43210",
      poaStatus: "Verified",
      signatureReady: true,
      dscSerial: "DSC-8839-IN-CLASS3-2027",
      dscExpiry: "12 Oct 2027",
      bidLeadName: "Vikas Kumar (Lead Bid Strategist)",
      technicalReviewer: "Arindam Roy (Chief Solution Architect)",
      financialReviewer: "Priya Sharma (Finance Controller)",
    },
    tenderFeeDetails: {
      amountDisplay: "₹5,000 + 18% GST (₹5,900)",
      status: "Paid & Verified",
      paymentMode: "Internet Banking (SBI Corporate e-Pay)",
      transactionRef: "SBIN20260310928371",
      paymentDate: "10 Mar 2026, 02:45 PM IST",
      receiptDocName: "SBI_Payment_Challan_SAJHA69.pdf",
    },
    emdComplianceDetails: {
      amountDisplay: "₹5,00,000",
      requiredPercentage: "3.33% of Contract Value",
      activeMode: "MSME_EXEMPTION",
      msmeEligible: true,
      msmeUdyamNumber: "UDYAM-MH-19-0048291",
      exemptionDocName: "MSME_Rule_170_Self_Declaration_SAJHA69.pdf",
      bgBankName: "State Bank of India (Commercial Branch)",
      bgNumber: "BG-9920-2026-MUM",
      bgValidUntil: "07 Sep 2026",
      bgDocName: "SBI_Bank_Guarantee_Scanned_SAJHA69.pdf",
      rtgsUtr: "HDFC20260310009281",
      rtgsDate: "10 Mar 2026",
      rtgsDocName: "RTGS_Remittance_Slip_SAJHA69.pdf",
    },
  },
  {
    id: "tender-rail-104",
    tenderNumber: "ER-S&T-2026-104",
    title: "Supply, Installation & Maintenance of Cloud CCTV Video Surveillance System across Eastern Railway Stations",
    organization: "Eastern Railway Zone, Indian Railways",
    department: "Signal & Telecommunication Department",
    location: "Kolkata, West Bengal",
    publishDate: "15 Feb 2026",
    submissionDeadline: "15 Apr 2026, 05:00 PM",
    technicalOpeningDate: "16 Apr 2026, 11:00 AM",
    estimatedValueDisplay: "₹4,80,00,000 (₹4.80 Cr)",
    tenderFeeDisplay: "₹11,800",
    emdDisplay: "₹9,60,000",
    emdStatus: "Exempt (MSME)",
    readinessScore: 88,
    winProbability: 85,
    decision: "GO",
    status: "Qualified",
    submissionMode: "IREPS (Indian Railways e-Procurement System)",
    turnoverRequired: "₹3.00 Cr",
    companyTurnover: "₹16.20 Cr",
    scopeSummary: "Procurement, field deployment, network cabling, edge AI analytics servers, and 5-year 24x7 operational monitoring for CCTV surveillance network across 42 railway stations in Eastern zone.",
    keyDates: [
      { label: "Tender Published", date: "15 Feb 2026", isPassed: true },
      { label: "Pre-Bid Meeting", date: "01 Mar 2026", isPassed: true },
      { label: "Bid Due Date", date: "15 Apr 2026, 05:00 PM", isPassed: false },
      { label: "Bid Opening", date: "16 Apr 2026", isPassed: false },
    ],
    tags: ["Surveillance", "AI Analytics", "Railway", "Infrastructure"],
    commercialTerms: {
      contractDuration: "6 Months (Supply & Install) + 5 Years (24x7 AMC)",
      performanceSecurityPBG: "3% of Total Contract Value",
      bidValidity: "120 Days from Opening Date",
      penaltyClause: "1.0% per week of delay (Max 10%)",
      coversCount: "2-Cover (IREPS Packet A & Packet B)",
      consortiumRule: "Joint Venture Allowed (Max 2 Partners, Lead 51%)",
      msmePolicy: "EMD Exempt: Yes | Turnover Relaxation: Available as per Railway Board",
    },
    paymentMilestones: [
      { phase: "Phase 1", percentage: "60%", milestoneTitle: "Supply & Delivery of Hardware", description: "On receipt of materials at station store with inspection certificate." },
      { phase: "Phase 2", percentage: "30%", milestoneTitle: "Installation & Commissioning", description: "Successful installation, live camera feed streaming, and signoff." },
      { phase: "Phase 3", percentage: "10%", milestoneTitle: "Final Acceptance & PG Test", description: "30-day trial run without failure and handover to S&T department." },
    ],
    sourceDocuments: [
      {
        id: "doc-rail-1",
        name: "Tender_Document_ER_ST_CCTV_2026.pdf",
        size: "14.2 MB",
        pages: 210,
        type: "RFP",
        date: "15 Feb 2026",
      },
    ],
    requirements: [
      {
        id: "req-rail-1",
        category: "financial",
        categoryLabel: "Financial Turnover",
        title: "Minimum Turnover of ₹3.00 Cr",
        ruleDescription: "Average turnover of last 3 FYs must be greater than or equal to ₹3.00 Crores.",
        thresholdValue: "₹3.00 Cr Turnover",
        proofRequired: "CA certified turnover certificate with UDIN.",
        mandatory: true,
        iconName: "TrendingUp",
      },
      {
        id: "req-rail-2",
        category: "experience",
        categoryLabel: "Past Project Experience",
        title: "Railway / PSU CCTV Surveillance Deployment",
        ruleDescription: "Must have supplied & commissioned at least 2 similar surveillance projects of >= 100 cameras in the last 4 years.",
        thresholdValue: "2+ CCTV Deployments",
        proofRequired: "Completion certificates with client performance endorsement.",
        mandatory: true,
        iconName: "FolderGit2",
      },
      {
        id: "req-rail-3",
        category: "certifications",
        categoryLabel: "OEM Authorization & Quality",
        title: "Manufacturer Authorization Form (MAF)",
        ruleDescription: "OEM Authorization certificates for IP cameras, NVRs, and Video Analytics licenses.",
        thresholdValue: "Valid OEM MAF",
        proofRequired: "MAF letter on OEM letterhead.",
        mandatory: true,
        iconName: "Award",
      },
    ],
    disqualificationGates: [
      {
        id: "gate-rail-1",
        category: "Financial Gate",
        title: "Annual Turnover Eligibility Threshold",
        requiredValue: "Min. ₹3.00 Cr Avg. (Last 3 FYs)",
        companyValue: "₹16.20 Cr Average (5.4x Buffer)",
        status: "PASS",
        note: "Audited balance sheets with CA UDIN verified in Company Vault.",
        proofDocumentName: "CA_Audited_Turnover_Cert_UDIN_2025.pdf",
        iconName: "TrendingUp",
      },
      {
        id: "gate-rail-2",
        category: "Experience Gate",
        title: "PSU / Railway CCTV Surveillance Track Record",
        requiredValue: "Min. 2 Completed CCTV Projects (>=100 Cams)",
        companyValue: "2 Completed Railway / Metro Surveillance Contracts",
        status: "PASS",
        note: "Verified completion certificates for Metro Line 2 Surveillance and Western Railway Station CCTV.",
        proofDocumentName: "Railway_CCTV_Completion_Certificates.pdf",
        iconName: "FolderGit2",
      },
      {
        id: "gate-rail-3",
        category: "OEM Authorization",
        title: "Manufacturer Authorization Form (MAF)",
        requiredValue: "Direct Tier-1 OEM Authorization",
        companyValue: "Hikvision & Cisco Gold Partner Authorization",
        status: "PASS",
        note: "OEM warranty commitment letter for 5 years with direct spares support.",
        proofDocumentName: "OEM_MAF_Authorization_Letters_2026.pdf",
        iconName: "Award",
      },
    ],
    vaultAuditDocuments: [
      {
        id: "vdoc-rail-1",
        name: "Certificate of Incorporation (MCA)",
        category: "Corporate Registration",
        status: "verified",
        issueDate: "14 May 2019",
        fileSize: "1.2 MB",
        message: "CIN: U72900MH2019PTC328491 · Verified Active",
      },
      {
        id: "vdoc-rail-2",
        name: "MSME Udyam Registration Certificate",
        category: "MSME Exemption",
        status: "verified",
        issueDate: "Permanent",
        fileSize: "620 KB",
        message: "Eligible for 100% EMD Exemption under Rule 170 GFR",
      },
      {
        id: "vdoc-rail-3",
        name: "OEM Partner Authorization (MAF)",
        category: "OEM Proof",
        status: "verified",
        issueDate: "Jan 2026",
        fileSize: "2.1 MB",
        message: "Manufacturer Backed 5-Year Hardware Warranty",
      },
    ],
    qcbsScores: [
      {
        parameter: "1. Annual Turnover & Financial Liquidity",
        maxMarks: 25,
        earnedMarks: 25,
        evaluationBasis: "Turnover > ₹10 Cr qualifies for max 25 marks.",
      },
      {
        parameter: "2. CCTV & Surveillance Project Experience",
        maxMarks: 35,
        earnedMarks: 32,
        evaluationBasis: "2 Major PSU contracts executed with zero SLA failure penalty.",
      },
      {
        parameter: "3. Technical Architecture & Network SLA Blueprint",
        maxMarks: 25,
        earnedMarks: 20,
        evaluationBasis: "High-density fiber ring and cloud failover architecture.",
      },
      {
        parameter: "4. OEM Certification & Local Service Centers",
        maxMarks: 15,
        earnedMarks: 15,
        evaluationBasis: "Dedicated Eastern region service center in Kolkata.",
      },
    ],
    riskRadarItems: [
      {
        id: "risk-rail-1",
        severity: "low",
        title: "Station Site Clearance Timing",
        riskDescription: "Cabling across active railway platforms requires divisional railway safety clearances.",
        mitigationStrategy: "Include joint deployment calendar with Railway S&T officers in Technical Proposal.",
      },
    ],
    signatoryDetails: {
      companyName: "Tech Solutions Pvt Ltd",
      hqLocation: "Tech Park, GS Road, Guwahati & Andheri East, Mumbai",
      pan: "AABCT8291M",
      gstin: "27AABCT8291M1Z8",
      cin: "U72900MH2019PTC328491",
      udyamRegistration: "UDYAM-MH-19-0048291",
      signatoryName: "Vikas Kumar",
      signatoryTitle: "Director & Authorized Bid Representative",
      signatoryEmail: "vikasfrontenddeveloper007@gmail.com",
      signatoryPhone: "+91 98765 43210",
      poaStatus: "Verified",
      signatureReady: true,
      dscSerial: "DSC-8839-IN-CLASS3-2027",
      dscExpiry: "12 Oct 2027",
      bidLeadName: "Vikas Kumar (Lead Bid Strategist)",
      technicalReviewer: "Arindam Roy (Chief Solution Architect)",
      financialReviewer: "Priya Sharma (Finance Controller)",
    },
  },
  {
    id: "tender-smart-mumbai-22",
    tenderNumber: "BMC-IT-2026-089",
    title: "Implementation of AI-Powered Traffic Management & Automated Violation Detection Command Centre",
    organization: "Brihanmumbai Municipal Corporation (BMC)",
    department: "Information Technology & Traffic Cell",
    location: "Mumbai, Maharashtra",
    publishDate: "20 Mar 2026",
    submissionDeadline: "05 May 2026, 04:00 PM",
    technicalOpeningDate: "06 May 2026, 03:00 PM",
    estimatedValueDisplay: "₹12,50,00,000 (₹12.50 Cr)",
    tenderFeeDisplay: "₹25,000",
    emdDisplay: "₹25,00,000",
    emdStatus: "Pending Payment",
    readinessScore: 64,
    winProbability: 60,
    decision: "IN REVIEW",
    status: "In Review",
    submissionMode: "MahaTenders Portal",
    turnoverRequired: "₹10.00 Cr",
    companyTurnover: "₹16.20 Cr",
    scopeSummary: "Turnkey development of smart traffic signal automation, automated number plate recognition (ANPR), RLVD detection, central video management dashboard, and integration with Mumbai Police e-Challan gateway.",
    keyDates: [
      { label: "Notification", date: "20 Mar 2026", isPassed: true },
      { label: "Pre-Bid Queries", date: "05 Apr 2026", isPassed: false },
      { label: "Submission Deadline", date: "05 May 2026, 04:00 PM", isPassed: false },
    ],
    tags: ["Smart City", "AI Traffic", "ANPR", "IoT"],
    commercialTerms: {
      contractDuration: "18 Months (Rollout) + 5 Years (City-wide SLA Operations)",
      performanceSecurityPBG: "10% of Contract Value",
      bidValidity: "180 Days",
      penaltyClause: "0.5% per week (Max 10%) + SLA penalty per outage hour",
      coversCount: "3-Cover System (Cover 1: EMD/Fee, Cover 2: Tech, Cover 3: Price)",
      consortiumRule: "Consortium Allowed (Up to 3 Members, Lead 51% & Indian Entity)",
      msmePolicy: "EMD Exempt: Not Eligible (Tender Value > ₹10 Cr)",
    },
    paymentMilestones: [
      { phase: "Phase 1", percentage: "15%", milestoneTitle: "Site Survey & Command Center Civil Handover", description: "Joint site survey of 120 traffic intersections and command room readiness." },
      { phase: "Phase 2", percentage: "35%", milestoneTitle: "ANPR Cameras & Signal Hardware Delivery", description: "Supply of edge AI cameras, controller units, and fiber connectivity." },
      { phase: "Phase 3", percentage: "30%", milestoneTitle: "Command Center AI Software Integration", description: "e-Challan gateway sync, live traffic AI violation detection, and UAT." },
      { phase: "Phase 4", percentage: "20%", milestoneTitle: "5-Year SLA Operations (Quarterly)", description: "Quarterly payments tied to 99.5% uptime performance." },
    ],
    sourceDocuments: [
      {
        id: "doc-bmc-1",
        name: "RFP_BMC_AI_Traffic_Command_Center_2026.pdf",
        size: "22.5 MB",
        pages: 310,
        type: "RFP",
        date: "20 Mar 2026",
      },
    ],
    requirements: [
      {
        id: "req-bmc-1",
        category: "financial",
        categoryLabel: "Financial Turnover",
        title: "Minimum ₹10.00 Cr Turnover",
        ruleDescription: "Average 3-year turnover must exceed ₹10.00 Crores.",
        thresholdValue: "₹10.00 Cr Turnover",
        proofRequired: "Audited Financial Statements.",
        mandatory: true,
        iconName: "TrendingUp",
      },
      {
        id: "req-bmc-2",
        category: "manpower",
        categoryLabel: "Team & Manpower Strength",
        title: "50+ In-house AI/Data Engineers",
        ruleDescription: "Must have 50+ engineers with minimum 5 AI/Computer Vision specialists.",
        thresholdValue: "50+ Engineers",
        proofRequired: "Payroll & CVs of key experts.",
        mandatory: true,
        iconName: "Users",
      },
    ],
    disqualificationGates: [
      {
        id: "gate-bmc-1",
        category: "Financial Gate",
        title: "Annual Turnover Requirement (₹10 Cr+)",
        requiredValue: "Min. ₹10.00 Cr Avg Turnover",
        companyValue: "₹16.20 Cr Avg (Passes with 1.6x)",
        status: "PASS",
        note: "Meets mandatory financial threshold.",
        proofDocumentName: "Audited_Balance_Sheets_FY22_25.pdf",
        iconName: "TrendingUp",
      },
      {
        id: "gate-bmc-2",
        category: "Manpower Gate",
        title: "AI Computer Vision Specialists on Payroll",
        requiredValue: "Min. 5 Dedicated AI/CV Specialists",
        companyValue: "3 AI Specialists in Vault",
        status: "ACTION_REQUIRED",
        note: "Need 2 additional CV specialists resumes and EPF proof attached.",
        proofDocumentName: "AI_CV_Team_CVs_and_ECR.pdf",
        iconName: "Users",
      },
    ],
    vaultAuditDocuments: [
      {
        id: "vdoc-bmc-1",
        name: "ROC Incorporation & Memorandum of Association",
        category: "Corporate Registration",
        status: "verified",
        issueDate: "14 May 2019",
        fileSize: "1.2 MB",
        message: "CIN: U72900MH2019PTC328491 · Verified Active",
      },
      {
        id: "vdoc-bmc-2",
        name: "AI / Data Engineering Team Certifications",
        category: "Manpower Records",
        status: "action_needed",
        issueDate: "2025",
        fileSize: "3.4 MB",
        message: "Attach 2 CV engineer certifications for complete 5-member team score",
      },
    ],
    qcbsScores: [
      {
        parameter: "1. Financial Turnover & Net Worth",
        maxMarks: 20,
        earnedMarks: 18,
        evaluationBasis: "₹16.2 Cr vs ₹10 Cr required.",
      },
      {
        parameter: "2. AI Smart City / Traffic Management Experience",
        maxMarks: 35,
        earnedMarks: 22,
        evaluationBasis: "1 ANPR deployment project submitted; needs supplementary demo.",
      },
      {
        parameter: "3. Team & Computer Vision Key Personnel",
        maxMarks: 25,
        earnedMarks: 14,
        evaluationBasis: "3 AI specialists verified (5 required for full marks).",
      },
      {
        parameter: "4. ISO 27001 Security & Data Privacy Compliance",
        maxMarks: 20,
        earnedMarks: 10,
        evaluationBasis: "ISO 27001 certificate renewal needed.",
      },
    ],
    riskRadarItems: [
      {
        id: "risk-bmc-1",
        severity: "high",
        title: "EMD Amount of ₹25 Lakhs Required Upfront",
        riskDescription: "Tender value is > ₹10 Cr so MSME fee waiver does not apply to EMD. Bank Guarantee or RTGS required.",
        mitigationStrategy: "Generate BG request letter to HDFC / ICICI bank branch 10 days before due date.",
      },
    ],
    signatoryDetails: {
      companyName: "Tech Solutions Pvt Ltd",
      hqLocation: "Tech Park, GS Road, Guwahati & Andheri East, Mumbai",
      pan: "AABCT8291M",
      gstin: "27AABCT8291M1Z8",
      cin: "U72900MH2019PTC328491",
      udyamRegistration: "UDYAM-MH-19-0048291",
      signatoryName: "Vikas Kumar",
      signatoryTitle: "Director & Authorized Bid Representative",
      signatoryEmail: "vikasfrontenddeveloper007@gmail.com",
      signatoryPhone: "+91 98765 43210",
      poaStatus: "Verified",
      signatureReady: true,
      dscSerial: "DSC-8839-IN-CLASS3-2027",
      dscExpiry: "12 Oct 2027",
      bidLeadName: "Vikas Kumar (Lead Bid Strategist)",
      technicalReviewer: "Arindam Roy (Chief Solution Architect)",
      financialReviewer: "Priya Sharma (Finance Controller)",
    },
  },
];
