import { TenderV2, TabItemV2 } from "./types";

export const TABS_V2: TabItemV2[] = [
  {
    id: "overview",
    stepNumber: 1,
    label: "Overview & Scope",
    subtitle: "Parameters & AI Copilot",
    iconName: "FileText",
  },
  {
    id: "eligibility",
    stepNumber: 2,
    label: "Eligibility & Gates",
    subtitle: "Scorecard & Rules",
    iconName: "ShieldCheck",
  },
  {
    id: "payment",
    stepNumber: 3,
    label: "Payment Proof",
    subtitle: "EMD & Cover-1 Slip",
    iconName: "CreditCard",
  },
  {
    id: "proposal",
    stepNumber: 4,
    label: "Proposal Desk",
    subtitle: "AI Technical Drafts",
    iconName: "PenLine",
  },
  {
    id: "binder",
    stepNumber: 5,
    label: "PDF Binder",
    subtitle: "Master Pack & Export",
    iconName: "Library",
  },
];

export const STATIC_TENDERS_V2: TenderV2[] = [
  {
    id: "tender-sajha-69",
    tenderNumber: "SAJHA/69",
    title: "Development of Integrated Website and Mobile Application for Sports Authority of Jharkhand (SAJHA)",
    organization: "Sports Authority of Jharkhand (SAJHA)",
    department: "Department of Tourism, Arts, Culture, Sports & Youth Affairs",
    location: "Ranchi, Jharkhand",
    publishDate: "02 Mar 2026",
    submissionDeadline: "28 Mar 2026, 03:00 PM",
    technicalOpeningDate: "29 Mar 2026, 11:30 AM",
    estimatedValueDisplay: "₹1,50,00,000 (₹1.50 Cr)",
    tenderFeeDisplay: "₹5,900 (₹5,000 + 18% GST)",
    emdDisplay: "₹5,00,000",
    emdStatus: "Verified",
    readinessScore: 76,
    winProbability: 72,
    decision: "GO",
    status: "In Analysis",
    submissionMode: "Online (Jharkhand e-Procurement Portal)",
    turnoverRequired: "₹1.50 Cr",
    companyTurnover: "₹16.20 Cr",
    scopeSummary: "Sports Authority of Jharkhand (SAJHA) requires a turnkey partner for end-to-end design, cloud architecture, native mobile applications (iOS & Android), athlete enrollment portal, tournament management with live scoring, and 3-year post-deployment maintenance support.",
    keyDates: [
      { label: "RFP Publication", date: "02 Mar 2026", isPassed: true },
      { label: "Pre-Bid Query Deadline", date: "12 Mar 2026", isPassed: true },
      { label: "Bid Submission Deadline", date: "28 Mar 2026, 03:00 PM", isPassed: false },
      { label: "Technical Bid Opening", date: "29 Mar 2026, 11:30 AM", isPassed: false },
    ],
    tags: ["Mobile App", "Web Portal", "e-Governance", "Sports Tech", "Cloud Native"],
    requirements: [
      {
        id: "req-1",
        category: "financial",
        categoryLabel: "Financial Turnover",
        title: "Minimum Average Annual Turnover",
        ruleDescription: "The bidder must have an average annual financial turnover of at least ₹1.50 Crore during the last 3 financial years (FY 2022-23, FY 2023-24, FY 2024-25).",
        thresholdValue: "₹1.50 Cr Average Turnover",
        proofRequired: "Audited Balance Sheets with CA Certificate and UDIN.",
        mandatory: true,
        iconName: "TrendingUp",
      },
      {
        id: "req-2",
        category: "experience",
        categoryLabel: "Past Project Experience",
        title: "Minimum 3 Completed Government Projects",
        ruleDescription: "The bidder must have successfully executed and completed at least 3 software development / web portal / mobile app projects for Central/State Govt, PSUs, or Autonomous Bodies in the last 5 years.",
        thresholdValue: "3+ Completed Projects",
        proofRequired: "Client Work Orders, Agreement copies, and Work Completion / Satisfactory Certificates.",
        mandatory: true,
        iconName: "FolderGit2",
      },
      {
        id: "req-3",
        category: "vintage",
        categoryLabel: "Company Operational Vintage",
        title: "Minimum 3+ Years in IT/Software Operations",
        ruleDescription: "The bidding entity must be incorporated and actively operating in software engineering, mobile apps, and IT consulting services for at least 3 continuous years prior to RFP date.",
        thresholdValue: "3+ Years Active Operations",
        proofRequired: "Certificate of Incorporation (ROC / MCA) and Memorandum of Association (MoA).",
        mandatory: true,
        iconName: "Building2",
      },
      {
        id: "req-4",
        category: "manpower",
        categoryLabel: "Team & Manpower Strength",
        title: "Minimum 25+ In-House Technical Professionals",
        ruleDescription: "The agency must have at least 25 full-time qualified IT personnel (Project Managers, UI/UX Designers, Cloud Engineers, Full-Stack Devs, QA) on its active payroll.",
        thresholdValue: "25+ Full-Time Engineers",
        proofRequired: "EPF (Employees' Provident Fund) electronic challan returns / HR payroll declaration.",
        mandatory: true,
        iconName: "Users",
      },
      {
        id: "req-5",
        category: "certifications",
        categoryLabel: "Quality & Security Accreditations",
        title: "Active ISO 9001 & ISO 27001 Certifications",
        ruleDescription: "The bidder must possess valid and active certifications for ISO 9001:2015 (Quality Management) and ISO 27001:2013 (Information Security Management) or CMMI Level 3.",
        thresholdValue: "ISO 9001 & ISO 27001 / CMMI L3",
        proofRequired: "Valid copies of accreditation certificates issued by accredited certification bodies.",
        mandatory: true,
        iconName: "Award",
      },
      {
        id: "req-6",
        category: "legal",
        categoryLabel: "Debarment & Legal Undertaking",
        title: "Non-Blacklisting Undertaking",
        ruleDescription: "The bidder must not have been debarred, blacklisted, or banned by any Central/State Government department, PSU, or multilateral agency as of bid date.",
        thresholdValue: "Clean Legal Record",
        proofRequired: "Self-Declaration on ₹100 Non-Judicial Stamp Paper duly notarized.",
        mandatory: true,
        iconName: "ShieldAlert",
      },
      {
        id: "req-7",
        category: "legal",
        categoryLabel: "Statutory Registrations",
        title: "Valid GSTIN, PAN, and Tax Compliance",
        ruleDescription: "The bidder must hold an active PAN card, GST registration in India, and have filed up-to-date Income Tax and GST returns.",
        thresholdValue: "Active PAN & GSTIN",
        proofRequired: "GST Registration Certificate, PAN card copy, and latest 2 quarters GSTR-3B filings.",
        mandatory: true,
        iconName: "FileCheck2",
      },
    ],
  },
  {
    id: "tender-rail-104",
    tenderNumber: "ER-S&T-2026-104",
    title: "Supply, Installation & Maintenance of Cloud CCTV Video Surveillance System across Eastern Railway Stations",
    organization: "Eastern Railway Zone, Indian Railways",
    department: "Signal & Telecommunication Department",
    location: "Kolkata, West Bengal",
    publishDate: "15 Feb 2026",
    submissionDeadline: "15 Apr 2026, 05:00 PM",
    technicalOpeningDate: "16 Apr 2026, 11:00 AM",
    estimatedValueDisplay: "₹4,80,00,000 (₹4.80 Cr)",
    tenderFeeDisplay: "₹11,800",
    emdDisplay: "₹9,60,000",
    emdStatus: "Exempt (MSME)",
    readinessScore: 88,
    winProbability: 85,
    decision: "GO",
    status: "Qualified",
    submissionMode: "IREPS (Indian Railways e-Procurement System)",
    turnoverRequired: "₹3.00 Cr",
    companyTurnover: "₹16.20 Cr",
    scopeSummary: "Procurement, field deployment, network cabling, edge AI analytics servers, and 5-year 24x7 operational monitoring for CCTV surveillance network across 42 railway stations in Eastern zone.",
    keyDates: [
      { label: "Tender Published", date: "15 Feb 2026", isPassed: true },
      { label: "Pre-Bid Meeting", date: "01 Mar 2026", isPassed: true },
      { label: "Bid Due Date", date: "15 Apr 2026, 05:00 PM", isPassed: false },
      { label: "Bid Opening", date: "16 Apr 2026", isPassed: false },
    ],
    tags: ["Surveillance", "AI Analytics", "Railway", "Infrastructure"],
    requirements: [
      {
        id: "req-rail-1",
        category: "financial",
        categoryLabel: "Financial Turnover",
        title: "Minimum Turnover of ₹3.00 Cr",
        ruleDescription: "Average turnover of last 3 FYs must be greater than or equal to ₹3.00 Crores.",
        thresholdValue: "₹3.00 Cr Turnover",
        proofRequired: "CA certified turnover certificate with UDIN.",
        mandatory: true,
        iconName: "TrendingUp",
      },
      {
        id: "req-rail-2",
        category: "experience",
        categoryLabel: "Past Project Experience",
        title: "Railway / PSU CCTV Surveillance Deployment",
        ruleDescription: "Must have supplied & commissioned at least 2 similar surveillance projects of >= 100 cameras in the last 4 years.",
        thresholdValue: "2+ CCTV Deployments",
        proofRequired: "Completion certificates with client performance endorsement.",
        mandatory: true,
        iconName: "FolderGit2",
      },
      {
        id: "req-rail-3",
        category: "certifications",
        categoryLabel: "OEM Authorization & Quality",
        title: "Manufacturer Authorization Form (MAF)",
        ruleDescription: "OEM Authorization certificates for IP cameras, NVRs, and Video Analytics licenses.",
        thresholdValue: "Valid OEM MAF",
        proofRequired: "MAF letter on OEM letterhead.",
        mandatory: true,
        iconName: "Award",
      },
    ],
  },
  {
    id: "tender-smart-mumbai-22",
    tenderNumber: "BMC-IT-2026-089",
    title: "Implementation of AI-Powered Traffic Management & Automated Violation Detection Command Centre",
    organization: "Brihanmumbai Municipal Corporation (BMC)",
    department: "Information Technology & Traffic Cell",
    location: "Mumbai, Maharashtra",
    publishDate: "20 Mar 2026",
    submissionDeadline: "05 May 2026, 04:00 PM",
    technicalOpeningDate: "06 May 2026, 03:00 PM",
    estimatedValueDisplay: "₹12,50,00,000 (₹12.50 Cr)",
    tenderFeeDisplay: "₹25,000",
    emdDisplay: "₹25,00,000",
    emdStatus: "Pending Payment",
    readinessScore: 64,
    winProbability: 60,
    decision: "IN REVIEW",
    status: "In Review",
    submissionMode: "MahaTenders Portal",
    turnoverRequired: "₹10.00 Cr",
    companyTurnover: "₹16.20 Cr",
    scopeSummary: "Turnkey development of smart traffic signal automation, automated number plate recognition (ANPR), RLVD detection, central video management dashboard, and integration with Mumbai Police e-Challan gateway.",
    keyDates: [
      { label: "Notification", date: "20 Mar 2026", isPassed: true },
      { label: "Pre-Bid Queries", date: "05 Apr 2026", isPassed: false },
      { label: "Submission Deadline", date: "05 May 2026, 04:00 PM", isPassed: false },
    ],
    tags: ["Smart City", "AI Traffic", "ANPR", "IoT"],
    requirements: [
      {
        id: "req-bmc-1",
        category: "financial",
        categoryLabel: "Financial Turnover",
        title: "Minimum ₹10.00 Cr Turnover",
        ruleDescription: "Average 3-year turnover must exceed ₹10.00 Crores.",
        thresholdValue: "₹10.00 Cr Turnover",
        proofRequired: "Audited Financial Statements.",
        mandatory: true,
        iconName: "TrendingUp",
      },
      {
        id: "req-bmc-2",
        category: "manpower",
        categoryLabel: "Team & Manpower Strength",
        title: "50+ In-house AI/Data Engineers",
        ruleDescription: "Must have 50+ engineers with minimum 5 AI/Computer Vision specialists.",
        thresholdValue: "50+ Engineers",
        proofRequired: "Payroll & CVs of key experts.",
        mandatory: true,
        iconName: "Users",
      },
    ],
  },
];
